name: gucentral
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dependencies:
  all_sensors: ^0.4.2
  auto_size_text: ^3.0.0
  awesome_notifications: any
  cloud_firestore: ^4.6.0
  cupertino_icons: ^1.0.2
  data_table_2: ^2.3.12
  date_picker_widget: ^0.0.4
  dropdown_button2: ^2.0.0
  fading_edge_scrollview: ^3.0.0
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_linkify: ^5.0.2
  flutter_native_splash: ^2.2.19
  flutter_polyline_points: ^1.0.0
  flutter_riverpod: ^2.3.6
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.2
  flutter_time_picker_spinner: ^2.0.0
  flutter_zoom_drawer: ^3.0.3
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.6
  hijri: ^3.0.0
  http: ^0.13.5
  intl: ^0.18.0
  jumping_dot: ^0.0.4
  lazy_load_indexed_stack: ^0.1.4
  linkwell: ^2.0.6
  local_auth: ^2.1.6
  location: ^4.4.0
  ntlm: ^2.0.1
  percent_indicator: ^4.2.3
  provider: ^6.0.5
  pull_to_refresh: ^2.0.0
  reorderables: ^0.6.0
  rotating_icon_button: ^1.0.0
  sensors_plus: ^2.0.2
  sensors_plus_web: ^1.1.2
  settings_ui: ^2.0.2
  shared_preferences: ^2.0.18
  simple_animations: ^5.0.0+3
  syncfusion_flutter_calendar: ^20.4.54
  table_calendar: ^3.0.9
  timeago: ^3.4.0
  transitioned_indexed_stack: ^1.0.2
  vibration: ^1.7.6
  vibration_web: ^1.6.5
  webdriver: ^3.0.2
  wtf_sliding_sheet: ^0.6.1

flutter_native_splash:
  color: "#141518"
  # color: "#ffffff"
  # color_dark: "#141518"
  image: assets/images/main-logo.png

flutter_launcher_icons:
  # android: "launcher_icon"
  ios: true
  image_path: "assets/app.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/dino/
    - assets/images/cacti/
    - assets/images/ptera/
    - assets/images/
    - assets/app.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Bold.ttf #700
        - asset: assets/fonts/Outfit-Medium.ttf #500
        - asset: assets/fonts/Outfit-Regular.ttf #400
        - asset: assets/fonts/Outfit-SemiBold.ttf #600
        - asset: assets/fonts/Outfit-Light.ttf #300
        - asset: assets/fonts/Outfit-ExtraBold.ttf #800

    - family: ChromeDino
      fonts:
        - asset: assets\fonts\PressStart2P-Regular.ttf
          # weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
