// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPAkKoyClAtOSbgaATUEi-3tQRy3LPo-8',
    appId: '1:556091875139:web:aa1a6e64badade6ce4d9f6',
    messagingSenderId: '556091875139',
    projectId: 'gucentrall',
    authDomain: 'gucentrall.firebaseapp.com',
    storageBucket: 'gucentrall.appspot.com',
    measurementId: 'G-HFHG56WHHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnVyiBr8hD8wkdvMqPh5TVHj5ENTgLz9o',
    appId: '1:556091875139:android:355dd6a900b6a7c9e4d9f6',
    messagingSenderId: '556091875139',
    projectId: 'gucentrall',
    storageBucket: 'gucentrall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMysLPZT6Ah-WNgDhFtZ1ZI8z7z3UhkSg',
    appId: '1:556091875139:ios:49b9ee5dace60b71e4d9f6',
    messagingSenderId: '556091875139',
    projectId: 'gucentrall',
    storageBucket: 'gucentrall.appspot.com',
    iosClientId: '556091875139-0jkdnthj86345nir02ornjijphg18ft7.apps.googleusercontent.com',
    iosBundleId: 'com.example.gucentral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMysLPZT6Ah-WNgDhFtZ1ZI8z7z3UhkSg',
    appId: '1:556091875139:ios:49b9ee5dace60b71e4d9f6',
    messagingSenderId: '556091875139',
    projectId: 'gucentrall',
    storageBucket: 'gucentrall.appspot.com',
    iosClientId: '556091875139-0jkdnthj86345nir02ornjijphg18ft7.apps.googleusercontent.com',
    iosBundleId: 'com.example.gucentral',
  );
}
